#this workflow will build a python file then 
#run a unit test routine on the file

name: CI
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: running the file first
      run: python circles.py
      
    
