#this workflow will build a python file then 
#run a unit test routine on the file

name: CI
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
#   script:
#     - name: setup python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.8'
  build1: 
    runs-on: [self-hosted, linux]
    steps:
    - name: run the app
#     - run: |
    - run: cd /home/sherif/workspace/cicd-python/
    - run: rm * -rf
    - run: git clone https://github.com/Sherif-Elshafei/CICD.git
    - run: cd CICD
    - run: python3 -m unittest test_circles2.py
        
